on:
  push:
    tags:
    - 'v*'

name: Release

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Set up node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
        id: node

      - name: Checkout code
        uses: actions/checkout@v2
        id: checkout
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build project
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./build/asuwave_${{ steps.checkout.outputs.tag }}_darwin_amd64.zip
            ./build/asuwave_${{ steps.checkout.outputs.tag }}_darwin_arm64.zip
            ./build/asuwave_${{ steps.checkout.outputs.tag }}_linux_amd64.zip
            ./build/asuwave_${{ steps.checkout.outputs.tag }}_linux_arm64.zip
            ./build/asuwave_${{ steps.checkout.outputs.tag }}_windows_amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
