on:
  push:
    tags:
    - 'v*'

name: Release

jobs:
  ubuntu-build:
    name: Ubuntu build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Set up node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
        id: node

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: |
            ./build/*.zip
            !./build/*_windows_amd64.zip

  windows-build:
    name: Windows build
    runs-on: windows-latest
    steps:

      - name: Set up upx
        run: choco install upx

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Set up node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
        id: node

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: .\build.ps1

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: .\build\*_windows_amd64.zip

  release:
    name: Release
    needs: [ubuntu-build, windows-build]
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: ./build/

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./build/asuwave_${{ steps.vars.outputs.tag }}_darwin_amd64.zip
            ./build/asuwave_${{ steps.vars.outputs.tag }}_darwin_arm64.zip
            ./build/asuwave_${{ steps.vars.outputs.tag }}_linux_amd64.zip
            ./build/asuwave_${{ steps.vars.outputs.tag }}_linux_arm64.zip
            ./build/asuwave_${{ steps.vars.outputs.tag }}_windows_amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
